//-----------------------------------------------------------------------
// <copyright file="JsonStructureDocumentExtensions.cs" company="NSwag">
//     Copyright (c) Rico Suter. All rights reserved.
// </copyright>
// <license>https://github.com/RicoSuter/NSwag/blob/master/LICENSE.md</license>
//-----------------------------------------------------------------------

using System.Runtime.CompilerServices;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NSwag.JsonStructure.Model;

namespace NSwag.JsonStructure.OpenApi
{
    /// <summary>Attaches lifted JSON Structure documents to OpenAPI documents without serializing them.</summary>
    public static class JsonStructureDocumentExtensions
    {
        private static readonly ConditionalWeakTable<OpenApiDocument, JsonStructureDocumentModel> Models = new();
        private static readonly ConditionalWeakTable<OpenApiDocument, Dictionary<string, JsonStructureDocument>> Generated = new();

        /// <summary>Registers a schema generated by an NSwag document generator.</summary>
        public static void RegisterGeneratedSchema(OpenApiDocument document, string correlationKey, JsonStructureDocument schema)
        {
            if (document == null) throw new ArgumentNullException(nameof(document));
            if (correlationKey == null) throw new ArgumentNullException(nameof(correlationKey));
            if (schema == null) throw new ArgumentNullException(nameof(schema));

            if (!Generated.TryGetValue(document, out var schemas))
            {
                schemas = new Dictionary<string, JsonStructureDocument>(StringComparer.Ordinal);
                Generated.Add(document, schemas);
            }

            schemas[correlationKey] = schema;
        }

        /// <summary>Attaches lifted JSON Structure documents to an OpenAPI document.</summary>
        /// <param name="document">The OpenAPI document.</param>
        /// <param name="model">The lifted JSON Structure model.</param>
        public static void AttachJsonStructureDocumentModel(this OpenApiDocument document, JsonStructureDocumentModel model)
        {
            if (document == null)
            {
                throw new ArgumentNullException(nameof(document));
            }

            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            Models.Remove(document);
            Models.Add(document, model);
        }

        /// <summary>Attaches lifted JSON Structure documents to an OpenAPI document.</summary>
        /// <param name="document">The OpenAPI document.</param>
        /// <param name="preprocessResult">The preprocessing result.</param>
        public static void AttachJsonStructureDocumentModel(this OpenApiDocument document, JsonStructurePreprocessResult preprocessResult)
        {
            if (preprocessResult == null)
            {
                throw new ArgumentNullException(nameof(preprocessResult));
            }

            document.AttachJsonStructureDocumentModel(new JsonStructureDocumentModel(preprocessResult.LiftedSchemas));
        }

        /// <summary>Gets the lifted JSON Structure model attached to an OpenAPI document.</summary>
        /// <param name="document">The OpenAPI document.</param>
        /// <returns>The attached model, or <c>null</c> when no model is attached.</returns>
        public static JsonStructureDocumentModel GetJsonStructureDocumentModel(this OpenApiDocument document)
        {
            if (document == null)
            {
                throw new ArgumentNullException(nameof(document));
            }

            Models.TryGetValue(document, out var model);
            Generated.TryGetValue(document, out var generated);
            if (model == null && generated == null)
            {
                return null;
            }

            if (generated == null || generated.Count == 0)
            {
                return model;
            }

            var schemas = model?.LiftedSchemas.ToDictionary(pair => pair.Key, pair => pair.Value, StringComparer.Ordinal) ??
                          new Dictionary<string, JsonStructureDocument>(StringComparer.Ordinal);
            foreach (var pair in generated) schemas[pair.Key] = pair.Value;
            return new JsonStructureDocumentModel(schemas);
        }

        /// <summary>Gets a lifted JSON Structure document by its OpenAPI JSON Pointer.</summary>
        /// <param name="document">The OpenAPI document.</param>
        /// <param name="pointer">The OpenAPI JSON Pointer correlation key.</param>
        /// <returns>The lifted document, or <c>null</c> when it is not present.</returns>
        public static JsonStructureDocument GetJsonStructureDocument(this OpenApiDocument document, string pointer)
        {
            if (pointer == null)
            {
                throw new ArgumentNullException(nameof(pointer));
            }

            return document.GetJsonStructureDocumentModel()?.Get(pointer);
        }

        /// <summary>Tries to get the lifted JSON Structure model attached to an OpenAPI document.</summary>
        public static bool TryGetJsonStructureDocumentModel(this OpenApiDocument document, out JsonStructureDocumentModel model)
        {
            if (document == null)
            {
                throw new ArgumentNullException(nameof(document));
            }

            model = document.GetJsonStructureDocumentModel();
            return model != null;
        }

        /// <summary>Restores lifted JSON Structure source JSON into a serialized OpenAPI document.</summary>
        public static string RestoreJson(OpenApiDocument document, string json, Formatting formatting)
        {
            Models.TryGetValue(document, out var model);
            Generated.TryGetValue(document, out var generated);
            if (model == null && generated == null)
            {
                return json;
            }

            var root = JObject.Parse(json);
            var allSchemas = new Dictionary<string, JsonStructureDocument>(StringComparer.Ordinal);
            if (model != null)
            {
                foreach (var pair in model.LiftedSchemas) allSchemas[pair.Key] = pair.Value;
            }
            if (generated != null)
            {
                foreach (var pair in generated) allSchemas[pair.Key] = pair.Value;
            }
            var stubs = new HashSet<string>(StringComparer.Ordinal);
            if (root["components"]?["schemas"] is JObject existingSchemas)
            {
                foreach (var property in existingSchemas.Properties().ToList())
                {
                    if (property.Name.StartsWith("__JsonStructure_", StringComparison.Ordinal) &&
                        property.Value is JObject stub && stub["x-json-structure"]?.Value<bool>() == true)
                    {
                        stubs.Add(property.Name);
                    }
                }
            }

            foreach (var pair in allSchemas)
            {
                var hasPointer = TryGet(root, pair.Key, out var placeholder);
                if (!hasPointer)
                {
                    placeholder = FindPlaceholder(root, pair.Key);
                }

                if (placeholder == null || pair.Value.SourceJson == null)
                {
                    continue;
                }

                if (placeholder is JObject obj && obj["$ref"] is JValue reference &&
                    ((string)reference)?.StartsWith("#/components/schemas/", StringComparison.Ordinal) == true)
                {
                    var name = Decode(((string)reference).Substring("#/components/schemas/".Length));
                    if (root["components"]?["schemas"]?[name]?["x-json-structure"]?.Value<bool>() == true)
                    {
                        stubs.Add(name);
                    }
                }

                if (hasPointer)
                {
                    Set(root, pair.Key, pair.Value.SourceJson.DeepClone());
                }
                else
                {
                    placeholder.Replace(pair.Value.SourceJson.DeepClone());
                }
            }

            if (root["components"]?["schemas"] is JObject schemas)
            {
                foreach (var stub in stubs)
                {
                    schemas.Remove(stub);
                }
            }

            return root.ToString(formatting);
        }

        private static JToken FindPlaceholder(JToken token, string key)
        {
            if (token is JObject obj)
            {
                if (obj[JsonStructureDocumentPreprocessor.CorrelationKeyExtensionName]?.Value<string>() == key)
                {
                    return obj;
                }

                foreach (var property in obj.Properties())
                {
                    var result = FindPlaceholder(property.Value, key);
                    if (result != null) return result;
                }
            }
            else if (token is JArray array)
            {
                foreach (var item in array)
                {
                    var result = FindPlaceholder(item, key);
                    if (result != null) return result;
                }
            }

            return null;
        }

        /// <summary>Restores an all-JSON-Structure document as OpenAPI 3.1.</summary>
        public static string RestoreJson31(OpenApiDocument document, string json, Formatting formatting)
        {
            if (!Models.TryGetValue(document, out var model) || model.LiftedSchemas.Count == 0)
            {
                throw new InvalidOperationException(
                    "OpenAPI 3.1 JSON Structure output requires an attached JSON Structure model.");
            }

            var root = JObject.Parse(json);
            if (!TryValidateAllJsonStructure(root, model, out var error))
            {
                throw new InvalidOperationException(
                    "OpenAPI 3.1 JSON Structure output supports only all-JSON-Structure documents: " + error);
            }

            var dialects = model.LiftedSchemas.Values
                .Select(value => value.SchemaUri)
                .Where(value => !string.IsNullOrEmpty(value))
                .Distinct(StringComparer.Ordinal)
                .ToList();
            if (dialects.Count != 1)
            {
                throw new InvalidOperationException(
                    "OpenAPI 3.1 JSON Structure output requires one common JSON Structure dialect.");
            }

            root["openapi"] = "3.1.0";
            root["jsonSchemaDialect"] = dialects[0];
            return RestoreJson(document, root.ToString(Formatting.None), formatting);
        }

        private static bool TryValidateAllJsonStructure(
            JObject root,
            JsonStructureDocumentModel model,
            out string error)
        {
            error = null;
            if (root["components"]?["schemas"] is not JObject schemas || schemas.Count == 0)
            {
                error = "the document has no lifted component schemas.";
                return false;
            }

            var correlations = new HashSet<string>(StringComparer.Ordinal);
            foreach (var property in schemas.Properties())
            {
                if (property.Value is not JObject stub ||
                    stub[JsonStructureDocumentPreprocessor.ExtensionName]?.Value<bool>() != true ||
                    stub[JsonStructureDocumentPreprocessor.CorrelationKeyExtensionName] is not JValue key ||
                    !model.LiftedSchemas.ContainsKey(key.Value<string>()))
                {
                    error = "ordinary OpenAPI schemas cannot be mixed with JSON Structure schemas.";
                    return false;
                }

                correlations.Add(key.Value<string>());
            }

            if (correlations.Count != model.LiftedSchemas.Count)
            {
                error = "every lifted JSON Structure schema must be represented by a component schema.";
                return false;
            }

            return ValidateSchemaPositions(root, string.Empty, false, schemas, out error);
        }

        private static bool ValidateSchemaPositions(
            JToken token,
            string pointer,
            bool isSchemaPosition,
            JObject schemas,
            out string error)
        {
            error = null;
            if (token is JObject obj)
            {
                if (isSchemaPosition)
                {
                    if (obj[JsonStructureDocumentPreprocessor.ExtensionName]?.Value<bool>() == true)
                    {
                        return true;
                    }

                    if (obj["$ref"] is JValue reference &&
                        ((string)reference)?.StartsWith("#/components/schemas/", StringComparison.Ordinal) == true)
                    {
                        var name = Decode(((string)reference).Substring("#/components/schemas/".Length));
                        if (schemas[name] is JObject target &&
                            target[JsonStructureDocumentPreprocessor.ExtensionName]?.Value<bool>() == true)
                        {
                            return true;
                        }
                    }

                    error = "a non-JSON-Structure schema was found at '" +
                        (string.IsNullOrEmpty(pointer) ? "/" : pointer) + "'.";
                    return false;
                }

                foreach (var property in obj.Properties())
                {
                    var childPointer = pointer + "/" + Encode(property.Name);
                    if (pointer == "/components/schemas")
                    {
                        if (!ValidateSchemaPositions(property.Value, childPointer, true, schemas, out error))
                        {
                            return false;
                        }
                    }
                    else if (IsSchemaMapProperty(property.Name) && property.Value is JObject map)
                    {
                        foreach (var mapProperty in map.Properties())
                        {
                            if (!ValidateSchemaPositions(mapProperty.Value,
                                childPointer + "/" + Encode(mapProperty.Name), true, schemas, out error))
                            {
                                return false;
                            }
                        }
                    }
                    else if (IsSchemaArrayProperty(property.Name) && property.Value is JArray array)
                    {
                        for (var i = 0; i < array.Count; i++)
                        {
                            if (!ValidateSchemaPositions(array[i], childPointer + "/" + i, isSchemaPosition, schemas, out error))
                            {
                                return false;
                            }
                        }
                    }
                    else
                    {
                        var childIsSchema = property.Name == "schema" ||
                            (isSchemaPosition && IsDirectSchemaProperty(property.Name));
                        if (!ValidateSchemaPositions(property.Value, childPointer, childIsSchema, schemas, out error))
                        {
                            return false;
                        }
                    }
                }
            }
            else if (token is JArray array)
            {
                for (var i = 0; i < array.Count; i++)
                {
                    if (!ValidateSchemaPositions(array[i], pointer + "/" + i, false, schemas, out error))
                    {
                        return false;
                    }
                }
            }

            return true;
        }

        private static bool IsDirectSchemaProperty(string name) =>
            name is "items" or "additionalProperties" or "unevaluatedProperties" or "contains" or
                "propertyNames" or "not" or "if" or "then" or "else";

        private static bool IsSchemaMapProperty(string name) =>
            name is "properties" or "patternProperties" or "$defs" or "definitions" or "dependentSchemas";

        private static bool IsSchemaArrayProperty(string name) =>
            name is "allOf" or "anyOf" or "oneOf" or "prefixItems";

        private static string Encode(string value) => value.Replace("~", "~0").Replace("/", "~1");

        private static bool TryGet(JToken token, string pointer, out JToken result)
        {
            result = token;
            if (pointer == "#")
            {
                return true;
            }

            if (!pointer.StartsWith("#/", StringComparison.Ordinal))
            {
                return false;
            }

            foreach (var segment in pointer.Substring(2).Split('/'))
            {
                result = result is JObject obj ? obj[Decode(segment)] :
                    result is JArray array && int.TryParse(Decode(segment), out var index) ? array[index] : null;
                if (result == null)
                {
                    return false;
                }
            }

            return true;
        }

        private static void Set(JObject root, string pointer, JToken value)
        {
            var segments = pointer.Substring(2).Split('/');
            JToken parent = root;
            for (var i = 0; i < segments.Length - 1; i++)
            {
                parent = parent is JObject obj ? obj[Decode(segments[i])] :
                    parent is JArray array && int.TryParse(Decode(segments[i]), System.Globalization.NumberStyles.None, System.Globalization.CultureInfo.InvariantCulture, out var index)
                        ? array[index] : null;
                if (parent == null)
                {
                    return;
                }
            }

            var last = Decode(segments[segments.Length - 1]);
            if (parent is JObject objParent)
            {
                objParent[last] = value;
            }
            else if (parent is JArray arrayParent)
            {
                if (int.TryParse(last, System.Globalization.NumberStyles.None, System.Globalization.CultureInfo.InvariantCulture, out var index))
                {
                    arrayParent[index] = value;
                }
            }
        }

        private static string Decode(string segment)
        {
            return segment.Replace("~1", "/").Replace("~0", "~");
        }
    }
}
